import { Repository } from '@/models'
import { QueryUser } from '@/query/types'

export const fakeData = {
  repos: [
    {
      id: '1',
      name: 'rocketship/ship',
      base_url: 'api.github.com/repos/rocketship/ship',
      service: 'github',
    },
  ] as Repository[],

  users: [
    {
      id: '1',
      name: 'Emily Johnson',
      username: 'emilyj11',
      avatar: 'https://i.pravatar.cc/150?img=1',
    },
    {
      id: '2',
      name: 'James Smith',
      username: 'jamess33',
      avatar: 'https://i.pravatar.cc/150?img=2',
    },
    {
      id: '3',
      name: 'Olivia Wilson',
      username: 'oliviaw8',
      avatar: 'https://i.pravatar.cc/150?img=3',
    },
    {
      id: '4',
      name: 'Ethan Lee',
      username: 'ethanl22',
      avatar: 'https://i.pravatar.cc/150?img=4',
    },
    {
      id: '5',
      name: 'Sophia Brown',
      username: 'sophiab15',
      avatar: 'https://i.pravatar.cc/150?img=5',
    },
    {
      id: '6',
      name: 'Daniel Kim',
      username: 'danielk34',
      avatar: 'https://i.pravatar.cc/150?img=6',
    },
    {
      id: '7',
      name: 'Ava Davis',
      username: 'avad20',
      avatar: 'https://i.pravatar.cc/150?img=7',
    },
    {
      id: '8',
      name: 'Michael Rodriguez',
      username: 'michaelr19',
      avatar: 'https://i.pravatar.cc/150?img=8',
    },
    {
      id: '9',
      name: 'Isabella Martinez',
      username: 'isabellam7',
      avatar: 'https://i.pravatar.cc/150?img=9',
    },
    {
      id: '10',
      name: 'William Nguyen',
      username: 'williamn14',
      avatar: 'https://i.pravatar.cc/150?img=10',
    },
  ] as QueryUser[],

  bugs: [
    'Navigation system, malfunction causing course deviation',
    'Fuel leak in propulsion system',
    'Life support systems malfunctioning',
    'Communications array failure',
    'Emergency power system failure',
    'Thruster engine vibration causing structural stress',
    'Navigation computer software bug causing erratic behavior',
    'Malfunctioning airlock preventing entry to the ship',
    'Oxygen recycler malfunction causing CO2 buildup',
    'Solar panel deployment mechanism stuck',
    'Artificial gravity generator malfunctioning',
    'Data transmission errors from scientific equipment',
    'Temperature control system failure',
    'Micro-meteoroid puncture causing pressure loss',
    'Thruster fuel injector clogged',
    'Radiation shielding system malfunction',
    'Power distribution network overload causing intermittent outages',
    'Computer system hack resulting in data loss and system instability',
    'Microgravity causing disorientation and balance problems',
    'Control panel buttons malfunctioning and producing unexpected results',
  ],

  features: [
    'Automated course correction to avoid hazards',
    'Real-time monitoring of fuel levels and consumption',
    'Personalized temperature and humidity controls in crew quarters',
    'Augmented reality displays for better situational awareness',
    'Integrated emergency escape pods',
    'Automated repair drones for external maintenance',
    'Advanced communication system for faster data transmission',
    'Recyclable water and waste management system',
    'Smart food dispensing and meal planning system',
    'Artificial intelligence-based crew assistance system',
    'Advanced airlock system for enhanced safety and security',
    'Automated docking and undocking system',
    'Self-repairing outer hull material',
    'Advanced power management and storage system',
    'Health monitoring system for crew members',
    'Advanced propulsion system for faster travel',
    'Smart cargo management system for efficient storage and retrieval',
    'Advanced gravitational simulation system for crew exercise',
    'Comprehensive fault tolerance and self-healing system',
    'Advanced life support system for extended missions in space.',
  ],

  pullTitles: [
    'Fix navigation system bug',
    'Refactor engine control code',
    'Implement new power management system',
    'Add emergency air supply functionality',
    'Update telemetry dashboard design',
    'Resolve life support module issue',
    'Improve communication system performance',
    'Integrate new sensor array system',
    'Implement new fuel efficiency algorithm',
    'Fix minor docking port alignment bug',
    'Refactor thruster control code',
    'Upgrade radiation shielding system',
    'Add new data visualization feature',
    'Fix minor life support sensor bug',
    'Optimize power distribution system',
    'Implement new autopilot system',
    'Upgrade navigation system accuracy',
    'Add new communication encryption feature',
    'Fix minor power management bug',
    'Refactor telemetry data handling code',
  ],
}
